-- TOTP login: accounts no longer require Google, and can authenticate with a
-- 6-digit code generated by an authenticator app (e.g. Apple Passwords).
ALTER TABLE users ALTER COLUMN google_id DROP NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS totp_secret_enc TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS totp_enabled BOOLEAN NOT NULL DEFAULT false;
